var GAME_LEVELS = [
  ["xv        x    x   x      x     x         x             x  x               x vx ",
   "x         x    x   x      x     x         x             v  x               x  x ",
   "v         x    x   x      x     x         x                                x  x ",
   "          x    x   x            x         x                                x  x ",
   "          x    x   x            x         v                                x  v ",
   "          x    x   x            x                                          v    ",
   "          x    v   x            x                                 xxx           ",
   "          x        x            x                   xx       xxxxxx!xx          ",
   "          x        x            x              xx          xxx   x!v!x          ",
   "          x                     x                               xxv vx          ",
   "          x                     x       xxxx                   xx               ",
   "          x                     x                            xxx            xx  ",
   "  xx                            v                          xxx               x  ",
   "  x                     b                                 xx                 x  ",
   "  x                                   xxxxx               x                  x  ",
   "  x          xxxx       b                                 x  p               x  ",
   "  x  @       x  x                                         x      xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxx                 xxxxxxxx   xxxxxxxxx  ",
   "                              x   x     x                  x                    ",
   "                              x!!!x     x!!!!!!!!!!!!!!!!!!x                    ",
   "                              x!!!x     x!!!!!!!!!!!!!!!!!!x                    ",
   "                              xxxxx     xxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                              ",
   "  xx                                                                                                          ",
   "  x                                                                                                           ",
   "  x           i        b b    b b    b b    b b                                                    p          ",
   "  x                     b      b      b      b                                           xxx    xxxxx         ",
   "  x  @                 b b    b b    b b    b b                                                               ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["         x      x          x                 x      x                                 x              x        ",
   "         x      x          x                 x      x                                 x              x        ",
   "         x      x          x                 v      x                                 x              x        ",
   "         x      x          x                        v                     i           x              x        ",
   "         x      x          x                                 xxxxxxx   xxxxx          x              x        ",
   "         x      x          xxx                                 x                      x              x        ",
   "         x      v            x                                 x                      x              v        ",
   "         x                   xxxx                b             x                      x                       ",
   "         x                     x                xxxxxxx   xxxxxx                      x                       ",
   "         x                     x                 x                                    v                       ",
   "         x                     x                 x                                                            ",
   "         x                     xxxxx             x                                                            ",
   "         x                         xxxx       xxxxxx                                                        xx",
   "         x                           v        x   x                                                       xxx ",
   "         x                                    x   x                                                    xxxx   ",
   "         v           x                     xxxx   x                                                 xxxx v    ",
   "                     x                  xxxx      v                                              xxxx v       ",
   "                     x                   x                                       xxxxxxx     xxxxx            ",
   "                     xxxxx               x                   xxxxx           xxxxx     xxxxxxx                ",
   "       xxxxxx          v x               x              xxxxxx   xxxxxxx   xxx  v      v    x                 ",
   "            xxxxx        xxxx        xxxxx           xxxx  v      v    xxxxx                x                 ",
   "             v  xx          xx      xx  v            x                   v                  v                 ",
   "  xx            x           x        x              xx                                                        ",
   "  x             x           x        x                                                                        ",
   "  x             x           x        x                                                                        ",
   "  x             xx          xx      xx                                                                        ",
   "  x  @                                                                   b                                    ",
   "  xxxxxxx                                                xxx     xx     xxx                   p               ",
   "        x                                     xxxxx                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
